[bell]
duration = 0

[colors.bright]
black = "#555555"
blue = "#8899ff"
cyan = "#88ffff"
green = "#55ff55"
magenta = "#ff88ff"
red = "#ff4444"
white = "#ffffff"
yellow = "#ffff22"

[colors.normal]
black = "#000000"
blue = "#5665ff"
cyan = "#50d2da"
green = "#1cdd15"
magenta = "#b052da"
red = "#ee0000"
white = "#dddddd"
yellow = "#ddcc33"

[colors.primary]
background = "#090909"
foreground = "#dddddd"

[env]
TERM = "xterm-256color"

[font]
size = 14
[font.normal]
family = "Fira Code"
style = "Regular"
[font.bold]
family = "Fira Code"
style = "Bold"
[font.italic]
family = "Fira Code"
style = "Italic"
[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"
[font.offset]
x = 1
y = 1
[font.glyph_offset]
x = 1
y = 1

[scrolling]
history = 50001
multiplier = 6

[window]
padding = { x = 13, y = 12 }
dynamic_padding = true
decorations = "Full"
startup_mode = "Windowed"
title = "Alacritty"
opacity = 1.0
blur = false
class = { instance = "Alacritty", general = "Alacritty" }

[[mouse.bindings]]
action = "Paste"
mods = "Shift"
mouse = "Middle"

[[mouse.bindings]]
action = "Copy"
mods = "Control"
mouse = "Middle"

[window.dimensions]
columns = 80
lines = 24

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 751
unfocused_hollow = true
thickness = 1.15

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\\\"' ()[]{}<>\\t"
save_to_clipboard = true

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u0001-\\u001F\\u007F-\\u009F<>\\\"\\\\s{-}\\\\^⟨⟩`]+"
command = "xdg-open"
post_processing = true
mouse.enabled = true
mouse.mods = "None"
binding = { key = "U", mods = "Control|Shift" }

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key1"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"
