[projects."/home/p"]
trust_level = "trusted"

[projects."/home/p/.xmonad"]
trust_level = "trusted"

[projects."/home/p/Projects/fii"]
trust_level = "trusted"

[projects."/home/p/dotfiles"]
trust_level = "trusted"

[ui.theme]
name = "dark-carbon-night"
